### ISSUE TITLE
Filtering overloaded methods

### ISSUE THREAD

**Issue by ansoni-san** [saltosystems/winrt-go#75]
I have this little change over here:
https://github.com/ansoni-san/winrt-go/commit/7d9c02ba980233cadc1c4a2075cb31b67d9e9d5f

To allow filtering out specific method overloads. I needed it to partially implement pairing without pulling in a heap of things I didn't want.

Is it worth raising as a pull request?

It basically changes the `shouldImplement` method to check the `overloadName` for a filter match as well. Both the `overloadName` and the original interface name (`methodDef.Name`) must be accepted for the method to be implemented. Since the default behavior is to accept a method that has no matches, this only has the effect of allowing negative matches on the overload name to take effect.

Nothing currently implemented in this project changed as a result, but it allowed me to get pairing working on Windows.

**Comment by jagobagascon** [comment]
What if we only use the overload method name?

Go doesn't support overloading and **I think it makes more sense to make each `-method-filter` point to a single generated Go method**.

It's a really [easy value to find](https://learn.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.bluetoothledevice.frombluetoothaddressasync?view=winrt-22621#overloads), and the change in the code is even simpler.

@aberasarte, @glerchundi I added #76 with the change. PTAL 🙏.

**Comment by glerchundi** [comment]
Much more explicit so I prefer that way.

**Comment by jagobagascon** [comment]
@ansoni-san I'm merging the PR and closing this issue. Feel free to reopen it if the solution does not satisfy your needs. 

Also feel free to make a PR with any method or class you require.

**Comment by ansoni-san** [comment]
Yeah that makes sense.

I can't see the behavior of including all permutations of a method as desirable, given that there's a need to minimize unnecessary surface area and unused code in this module. 

I would have preferred this behavior. I kept wishing it worked like this while trying to stop the whole world being pulled in from a few simple additions 😄🤔👌🏽

Given Microsoft's liberal use of overloading, better to be explicit. It would also guard against new things being pulled in automatically when they add things in the future.
