### ISSUE TITLE
Add support for Windows Hello framework

### ISSUE THREAD

**Issue by seppestas** [saltosystems/winrt-go#78]
I'm looking into using this project for generating Golang bindings around Windows Hello biometric authentication (Windows.Security.Credentials), with as main objective adding Windows hello as 2nd factor in saml2aws authentication. See https://github.com/Versent/saml2aws/issues/912.

If I get this working, I would like to send a PR to include this into this library. My plan is then to wrap it into a Golang library that could also support MacOS touch ID etc.

**Comment by seppestas** [comment]
I figured out that in order to use the features I require, I need (or at least it is easier) to use the [Microsoft webauthn win32 apis](https://github.com/microsoft/webauthn) instead. The [Windows Hello RT libraries](https://learn.microsoft.com/en-us/windows/uwp/security/microsoft-passport) only seem to be useful to set up new apps, not to integrate with existing Webauthn apps.

Note that [Chrome/Chromium and therefore probably also Edge use the webauthn win32 api](https://github.com/chromium/chromium/blob/db0f34dd13896435a29e7a19ac1f36bc50190b48/device/fido/win/webauthn_api.cc), not the WinRT API, even though the WinRT api is used in other places like the Chromium password manager. This makes me think the only way to use "Windows Hello" that is Webauthn compatible is through the win32 api.

Or, it could just be Microsoft being consistently inconsistent as always.

**Comment by jagobagascon** [comment]
Despite your latest findings, we would be more than happy to accept a PR to generate any WinRT classes you need. 

Apart from that there's not much we can do. So I'm closing this issue. Feel free to reopen it if you have any question.

Good luck on your research :)
