### ISSUE TITLE
Add support for abstract classes

### ISSUE THREAD

**Issue by seppestas** [saltosystems/winrt-go#79]
Some classes in the WinRT runtime are abstract, i.e they do not have a ctor but they do have static functions.

E.g. for #78, I need the `Windows.Security.Credentials.UI.UserConsentVerifier` (020000C0) class, which is an abstract class

```
flags [Public] [AutoLayout] [Class] [Abstract] [Sealed] [AnsiClass] [WindowsRuntime] (00004181)
```

winrt-go only allows runtime classes that have exactly one [InterfaceImpl](https://learn.microsoft.com/en-us/uwp/api/windows.foundation.metadata.defaultattribute?view=winrt-22621). However, an abstract class does not have any interface implementations / ctors.

This results in the following error:

```
go run github.com/saltosystems/winrt-go/cmd/winrt-go-gen -debug -class Windows.Security.Credentials.UI.UserConsentVerifier         
ts=2023-10-06T15:09:55.4201685Z level=debug msg="starting code generation" class=Windows.Security.Credentials.UI.UserConsentVerifier
ts=2023-10-06T15:09:55.4266126Z level=info msg="generating class" class=Windows.Security.Credentials.UI.UserConsentVerifier
ts=2023-10-06T15:09:55.4286881Z level=debug msg="found static interface" class=Windows.Security.Credentials.UI.IUserConsentVerifierStatics
ts=2023-10-06T15:09:55.4406154Z level=error err="type Windows.Security.Credentials.UI.UserConsentVerifier has no custom attribute Windows.Foundation.Metadata.DefaultAttribute"
```

**Comment by jagobagascon** [comment]
We were trying to generate the signature for abstract classes too, which makes no sense because they cannot be instantiated.

This PR (https://github.com/saltosystems/winrt-go/pull/80) should fix your issues :)
